#ifndef COLOR_SCHEME_YARU_LIGHT_H
#define COLOR_SCHEME_YARU_LIGHT_H

#include <QColor>

const QColor GLOBAL_BACKGROUND_COLOR = QColor(250, 250, 250);

const QColor GLOBAL_DEFAULT_TEXT_COLOR = QColor(63, 63, 63);

const QColor GLOBAL_SELECTED_BACKGROUND_COLOR = QColor(221, 221, 221);

#endif // COLOR_SCHEME_YARU_LIGHT_H
